In [18]:
# defining the neural network class
import numpy

class neuralNetwork:
    # function for initializing neural network
    # The "self" is used to represent the instance of the class. 
    # With this keyword, you can access the attributes and methods of the class in python.
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # set number of nodes in each nodes
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        self.lr = learningrate

        # Linking the weight matrices, wih, who
        # wih - weight linked with input and hidden layer
        # who = wieight linked with output and hidden layer
        # weights inside the arrays are w_i_j, where link is from node i to node j in the next layer
        # w11 w21 like input to hidden 1, input 2 to hidden 1.
        # w12 w22 etc visualized in paper. 
        self.wih = (numpy.random.rand(self.hnodes, self.inodes) - 0.5)
        self.who = (numpy.random.rand(self.onodes, self.hnodes) - 0.5)
    
        # updated code to initialize the weights
        #self.wih = (numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes)))        
        #self.who = (numpy.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes)))        

        # Using the sigmoid function as the activation function
        import scipy
        self.activation_function = lambda x: scipy.special.expit(x)
        # lambda is a special way of declaring functions which is anonymous(nameless) - 
        # it takes x as the input and returns the sigmoid function output using expit()

        pass
        #The pass statement is used as a placeholder for future code. 
        # When the pass statement is executed, nothing happens, 
        # but you avoid getting an error when empty code is not allowed. 
        # Empty code is not allowed in loops, function definitions, class definitions, or in if statements.
        

    # function for training the network
    def train(self, input_list, target_list):
        # feeding forward the signal from the input to the final layer
        # convert the input and target list into a 2D matrix and transpose
        inputs = numpy.array(input_list, ndmin=2).T

        # target list contains the training data in a list for training the network
        targets = numpy.array(target_list, ndmin=2).T

        #calculate signals emerging in the hidden layer from the input
        hidden_inputs = numpy.dot(self.wih, inputs)

        #calculate signals generated by the hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)

        #calculate signals generated into the final layer
        final_inputs = numpy.dot(self.who, hidden_outputs)

        #calculate signals emerging from the final layer (activation sheets by firing neurons)
        final_outputs = self.activation_function(final_inputs)

        #calculating the error between the target and actual for the neural network
        output_errors = targets - final_outputs
        
        # updating the weights according to the error for optimization and weight tuning
        # the output errors found above is the hidden layer errors.
        # the output/hidden layer errors need to be split by weight
        # then the split weight should be recombined with the hidden nodes to adjust/tune the network
        hidden_errors = numpy.dot(self.who.T, output_errors)

        # update the weights for the links between the hidden and output layer nodes
        self.who += self.lr  * numpy.dot((output_errors) * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs)
        pass

        # update the weights for the links between the input and the hidden  layer nodes
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))

    # function for implementing queries for the neural network
    # takes input to a network and returns the output of the network
    def query(self, input_list):
        # following will use numpy to convert the inputs into 2D array and then transpose with .T
        inputs = numpy.array(input_list, ndmin=2).T

        # calculate the signals emerging in the hidden layer from the inputs
        hidden_inputs = numpy.dot(self.wih, inputs)

        # calculate signals emerging from the hidden layer neurons to the next layer
        hidden_outputs = self.activation_function(hidden_inputs)

        # calculate the signals into the final output layer - will act as inputs to the final layer
        final_inputs = numpy.dot(self.who, hidden_outputs)

        #calculate the signals emerging from the final output layer
        final_outputs = self.activation_function(final_inputs)

        return final_outputs



In [25]:
# enter some small node and learning rate values for testing the network classes

input_nodes = 3
output_nodes = 3
# by changing the output nodes the the number of predicted output class will also change.

hidden_nodes = 3
learning_rate = 0.3

# creating instance of the neural network class
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

In [26]:
n.query([1.0, 0.5, -1.5])

array([[0.5561189 ],
       [0.54704723],
       [0.38915534]])

In [24]:
input_nodes2 = 3
output_nodes2 = 3
# by changing the output nodes the the number of predicted output class will also change.

hidden_nodes2 = 3
learning_rate2 = 0.1

# creating instance of the neural network class
n2= neuralNetwork(input_nodes2, hidden_nodes2, output_nodes2, learning_rate2)

n2.query([1.0, 0.5, -1.5])

array([[0.40416865],
       [0.52099938],
       [0.41705921]])

In [3]:
# use numpy to generate matrices of weight values.
# at first assign very low weight values, for instance between 0 and 1. 

import numpy

numpy.random.rand(3, 3) 
# 3*3 matirix with random numbers betwen 0 and 1 for weight values. 
# 3 nodes assigned previously so 3*3 matrix used.


array([[0.2661878 , 0.30378083, 0.65761156],
       [0.7498274 , 0.99460868, 0.468318  ],
       [0.00608374, 0.89341553, 0.25866533]])